name: Run linux commands
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
     - name: execute linux commands
       run: echo "Hello All"
  job2:
    needs: job1
    runs-on: ubuntu-24.04
    steps:
      - name: Execute set of linus commands
        run:
         hostname -s 
         
